### ISSUE TITLE
Publish lib

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/dap-kt#1]
@ALRubinger @leordev can y'all help me set up publishing this lib to sonatype and maven central? No worries if not, i can probably copy pasta my way through it

**Comment by ALRubinger** [comment]
@mistermoe Leo is PTO until next week. Yes I can. It may be a little more involved than a couple lines to set up because of how we set up the workflows to be easier to execute for devs, and matching Maven configs to match etc.

Relevant pieces:

* https://github.com/TBD54566975/tbdex-kt/blob/main/.github/workflows/release.yml#L51
* https://github.com/TBD54566975/tbdex-kt/blob/main/.maven_settings.xml
* https://github.com/TBD54566975/web5-kt/blob/main/pom.xml#L496
* https://github.com/TBD54566975/web5-kt/blob/main/pom.xml#L652
* https://github.com/TBD54566975/web5-kt/blob/main/pom.xml#L665
* https://github.com/TBD54566975/web5-kt/blob/main/pom.xml#L681

This even has me wondering if we should uplevel some of this build/release config stuff from `web5-parent` into a `tbd-parent` so they can be reused by projects that aren't children of Web5 (like `tbdex-kt` is).

Pair on it?
